create schema api-node;
use api-node;

create table if not exists project(
	id integer primary key generated by default as identity,
	name text not null check (name <> ''),
	priority integer not null,
	description text,
	deliverydate date not null 
);

create table if not exists tasts(
	id integer primary key generated by default as identity,
	name text not null check (name <> ''),
	done boolean,
	projectId integer references project(id)
);

-- consultas
select * from project;
select * from tasts;


-- insert project data
insert into project( name, priority, description, deliverydate )
values ('make a web app' , 1 , 'using javascript' , '2019-08-11');
insert into project( name, priority, description, deliverydate )
values ('make and app' , 1 , 'using dast' , '2019-08-15');
insert into project( name, priority, description, deliverydate )
values ('desktop' , 2 , 'using c++' , '2019-09-11');

-- insert tasks data
insert into tasts ( name, done, projectid )
values ('donwload vuejs' , false , 1);
insert into tasts ( name, done, projectid )
values ('create ui web ' , false , 1);
insert into tasts ( name, done, projectid )
values ('donwload flutter' , false , 2);
insert into tasts ( name, done, projectid )
values ('design ui' , false , 2);